### ISSUE TITLE
When a marker is clicked the map resets to defaults

### ISSUE THREAD

**Issue by jossmac** [dcousens/react-maps#3]
Specifically `center` and `zoom`. It can be pretty disorienting

**Comment by dcousens** [comment]
Can you elaborate?  I can't reproduce this.

**Comment by jossmac** [comment]
I can show you :)

Head over to http://jossandelizabeth.com then navigate to "locations" (sorry, can't link directly because react-router doesn't play nice with gh-pages), `zoom` in past the default and `drag` the map away from its `center`. Once you've done that click on one of the markers. When the info window is revealed the map snaps back to it's default `zoom` and `center`

**Comment by dcousens** [comment]
@jossmac I get the feeling this is because you haven't understood this warning:

``` javascript
      // WARNING: even if draggable/panControl is enable, props.center will still be authoritative
      draggable: false,
      panControl: false,
```

If you have a `center` prop,  it **will** be authoritative.  That is, it will dictate the center.
If `draggable` is `true` (which, it is in this case),  then,  you must **NOT** provide a center prop (except on initialization).
This is because,  on `componentWillUpdate`, it will update the maps center to the prop rather than ignoring it.

In your case, the onClick event is causing a re-render.
The map had already (secretly) been updated by `googlemaps`,  then react receives the `render`,  it then sets `center` back to what you provided.

Unfortunately,  I haven't yet found the best way to integrate google maps and react,  due to them following different event architectures.

**Comment by jossmac** [comment]
@dcousens thanks for the explanation. I've worked around this by explicitly setting the `center` to the selected marker's `lat/lng` and setting an invalid `zoom`.

Perhaps we could use the API's `panTo` function when `center` is updated? This would make for a nicer, animated, experience - just a thought

**Comment by dcousens** [comment]
@jossmac maybe `panUpdates` as a property? Or just `pan`?

**Comment by jossmac** [comment]
`panUpdates` is probably clearer, but yeah, that'd be sweet

**Comment by dcousens** [comment]
See https://github.com/dcousens/react-maps/issues/4
